language: node_js
node_js:
  - lts/*
before_script:
  - npm i
  - npm install -g npm
script:
  - npm run build
deploy:
  - provider: script
  script: git fetch --unshallow && git push https://$AZURE_WA_USERNAME:$AZURE_WA_PASSWORD@https://codenamesapp-deployslot.scm.azurewebsites.net:443/codenamesapp.git HEAD:refs/heads/master
  on: master

env:
  global:
    secure: aQbIucF/2NSCmEYbBQTFLZ9FNk3WVxiSyZv0mDU6W84mEyC31+67yX19baZ7oAJc7trNDPAH2NfdqBt8nWFqLGMP/UeC6gqn20xskFbhNST/kTwyEzY8YnQeMm/5DNaNyNibMVxt6Pz4gcVP9pYP3SzViWJkwbBZVq4L0NBMhIaYxjNvUcQ2PQM8DY0kJ4RmiiM5P8d9+uoYLGbWU/u82A+YAaweGTaWmvj2nBRuhhZgkLt4XPLnsR7UZemiZTnJQT16RfXzPx3X6t0babM2s64D27DT+R+RPbxjCdHAayHWDeBinqsAWNzpj1m82Z/UEUb4wE7C2CD5dFnBU5gTwiHEGivMlejUpmOFi+yLGiXhUBUlziMuZObSoUaTvfRSYoO0BmYqRES02BM118ZpFblgq/ZNwLaxzVBAiZzBz3Pzq6jHl30nKKnY2RlOEsQWFK0vTMXki6WOlF4gVpR2KG1ot6c8Yf22A0jxg7CFws2Gl/5wyFjNPvB6KGC9/JYr1kkXcBO1ngpCxH7zHr7WMz4Fb0IsSEEXQAj5jxYiaQ6ANILMxrJO0wR7mQ/u6ChpJtkn9M4EJWOF1qBtnH9UzQVIvUad3Jg6St1VIyTRF3jKkgmF44p5X0kUQwVEphFv/Fl3YiGFFm7CNrhmi0gyuyNJXHcFcruCaZV99W87pHA=
